ext {
  description = """Integrates ParSeq with the Apache ZooKeeper Library"""
  developers = [
    [id: 'axu', name: 'Ang Xu', email: 'axu@linkedin.com']
  ]
}


dependencies {
  api group: 'org.apache.zookeeper', name: 'zookeeper', version:'3.4.6'
  testImplementation project(':parseq-test-api')
  testImplementation group: 'org.testng', name: 'testng', version:'7.9.0'
  testImplementation group: 'com.linkedin.pegasus', name: 'd2', version:'2.6.0'
}
