ext {
  description = """Provides a convenient API for creating automatically batched tasks"""
}


dependencies {
  implementation group: 'org.hdrhistogram', name: 'HdrHistogram', version:'2.1.8'

  testImplementation project(':parseq-test-api')
  testImplementation group: 'org.testng', name: 'testng', version:'6.9.9'
  testImplementation group: 'org.slf4j', name: 'slf4j-simple', version:'1.7.12'
}
