ext {
  description = """Serves the tracevis tool for rendering graphviz diagrams"""
}

def jettyVersion = '9.3.0.v20150612'

configurations {
  tracevisTarGz
}

dependencies {
  implementation project(":parseq-exec")
  implementation project(":parseq-http-client")

  implementation project(path: ':parseq-tracevis', configuration: 'tracevisArtifacts')
  // If you didn't change any code in tracevis module, you can use below dependencies to build current module
  // implementation group: 'com.linkedin.parseq', name: 'parseq-tracevis', version: version, ext: 'tar.gz'
  implementation group: 'org.eclipse.jetty', name: 'jetty-server', version: jettyVersion
  implementation group: 'org.eclipse.jetty', name: 'jetty-servlet', version: jettyVersion
  implementation group: 'org.slf4j', name: 'slf4j-simple', version:'1.7.12'
}


task fatJar(type: Jar, dependsOn: [':parseq-tracevis:makeDist', ':parseq:jar', ':parseq-exec:jar', ':parseq-http-client:jar']) {
  archiveClassifier = 'jar-with-dependencies'
  from configurations.runtimeClasspath.collect {
    if (it.isDirectory()) {
      it
    } else if (it.name.endsWith('tar.gz')){
      tarTree(it)
    } else {
      zipTree(it)
    }
  }

  with jar
  manifest {
    attributes("Created-By": "Gradle",
        "Version": version,
        "Build-JDK": JavaVersion.current())
    attributes 'Main-Class': 'com.linkedin.parseq.TracevisServerJarMain'
  }
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

artifacts {
  archives fatJar
}
