ext {
  description = """Set of benchmarks for ParSeq"""
}

dependencies {
  implementation project(':parseq-batching')
  implementation group: 'org.hdrhistogram', name: 'HdrHistogram', version:'2.1.8'
  implementation group: 'org.slf4j', name: 'slf4j-simple', version:'2.0.9'
}

task fatJar(type: Jar) {
  mustRunAfter ':parseq:jar' // for some reason, gradle can't figure out this transitive dependency
  archiveClassifier = 'jar-with-dependencies'
  from { configurations.runtimeClasspath.collect { it.isDirectory()? it : zipTree(it) } }
  with jar
  manifest {
    attributes("Created-By": "Gradle",
        "Version": version,
        "Build-JDK": JavaVersion.current())
    attributes 'Main-Class': 'com.linkedin.parseq.PerfLarge'
  }
}

task executeJava(type: JavaExec) {
  main = "com.linkedin.parseq.PerfLarge"
  classpath = sourceSets.main.runtimeClasspath
}

artifacts {
  archives fatJar
}
